### ISSUE TITLE
sdk version higher in newer build

### ISSUE THREAD

**Issue by Hermain** [tuneduc/aws-glue-docker#7] opened 2021-02-02 15:38 UTC
I'm trying to build recreate your build on ubuntu (from maven:3.6-adoptopenjdk-8 to be precise) because I had problems installing great-expectations with the alpine image due to musl-libc.

Everything seems to work fine but unfortunately the jars downloaded have a different version than they have in your docker image.

I get:
```
"root@cf0eb94bb2ac:/opt/aws-glue-libs/jars# ls aws-java-sdk-core*
aws-java-sdk-core-1.11.774.jar" 
``` 

you got `aws-java-sdk-core-1.11.528.jar` in your image. 

The newer version causes the error `: java.lang.NoSuchFieldError: ENDPOINT_OVERRIDDEN` when executing glue code according to https://stackoverflow.com/a/64566641/7683711

Any idea how I can set the version of the aws-java-sdk jars to be downloaded?

**Comment by Hermain** [comment] 2021-02-03 10:02
FYI I just copied the jars from your image in a multistage dockerfile and now I don't get the error. Would be nice to be able to build it instead though.

**Comment by Julianobsg** [comment] 2021-02-03 13:15
Hi Hermain, thank you for opening the issue.

I was trying to check what happened and managed to rebuild in my last commit.

The problem is that we are not using this image in our workflow anymore. So is hard for us to keep track of the issues. Nonetheless, I uploaded the image on docker hub, feel free to check out.

Let me know if it worked fine and I'll close this issue.

**Comment by Hermain** [comment] 2021-02-04 13:50
@julianobsg thank you for taking the time.
I looked at your commit and noticed that it pretty certainly broke things because the line: 
echo -n "spark.driver.extraClassPath $GLUE_HOME/jars/*" > $SPARK_HOME/conf/spark-defaults.conf
will cause Problems. Also you change from getting the aws-glue-libs from master branch istead of glue-1.0. I think if you don't have time I would revert to the older container at least that worked and people like me could copy things from there :)

**Comment by Julianobsg** [comment] 2021-02-04 15:18
Will remove what was blocking the build and revert the rest. Will be easier for you to fork if needed.
Feel free to fork and open PRs if needed.
I've rebuilt and pushed back to the glue-1.0 version.

**Closed** 2021-02-26 15:31 UTC
